# Generated by Django 4.2.11 on 2026-01-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0012_alter_folderchatvisit_unique_together_and_more'),
        ('chat', '0002_rename_file_path_chatmessage_attached_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(db_index=True, max_length=500)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.userprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FolderChatVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(db_index=True, max_length=500)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.userprofile')),
            ],
            options={
                'unique_together': {('user', 'folder_path')},
            },
        ),
    ]
