"""
Django settings for vadrida project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path




# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_ig@9s8_3u#jib24eap(oydc$olvq)=)#4pb@9%u^=2)y8!6*$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'coreapi',
    'django_ratelimit',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE+= [ 
    'coreapi.middleware.LoginRequiredMiddleware'
]
ROOT_URLCONF = 'vadrida.urls'

BASE_DIR=Path(__file__).resolve().parent.parent

DOCUMENTS_FOLDER = r"G:\My Drive\1005.FOR_IT"

if not os.path.exists(DOCUMENTS_FOLDER):
    print(f"⚠️  WARNING: Documents folder not found: {DOCUMENTS_FOLDER}")
    print("Make sure:")
    print("1. Google Drive is running and synced")
    print("2. The path is correct")
    print("3. You have read permissions")

else:
    print(f"✓ Documents folder found: {DOCUMENTS_FOLDER}")
    print("Files inside DOCUMENTS_FOLDER:")
    print(os.listdir(DOCUMENTS_FOLDER))



ALLOWED_FILE_EXTENSIONS = [
    '.pdf', '.doc', '.docx', 
    '.xls', '.xlsx', '.csv',
    '.jpg', '.jpeg', '.png', '.gif', '.bmp',
    '.txt', '.zip'
]

# Maximum file size (in bytes) - 50MB default
MAX_FILE_SIZE = 50 * 1024 * 1024

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'core'/'templates', BASE_DIR / "coreapi" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vadrida.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR/'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL='noreply@vadrida.com'
ADMINS=[('Admin','admin@vadrida.com')]
CRISPY_TEMPLATE_PACK='bootstrap5'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}


SESSION_COOKIE_SECURE = True      # Only HTTPS
CSRF_COOKIE_SECURE = True         # Only HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 43200  # 12 hours
SESSION_ENGINE = 'django.contrib.sessions.backends.db' 
SESSION_SAVE_EVERY_REQUEST = True
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # local Redis
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000"
]


FULL_DATA_ROOT = os.path.join(BASE_DIR, "data")
# Folder to save generated PDFs in project
GENERATED_PDFS_ROOT = os.path.join(BASE_DIR , "generated_pdfs")
# Ensure directories exist
os.makedirs(GENERATED_PDFS_ROOT, exist_ok=True)
DOCUMENTS_ROOT = r"G:\My Drive\1005.FOR_IT"
