# Generated by Django 4.2.11 on 2025-12-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0006_sitevisitreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.userprofile'),
        ),
    ]
