# Generated by Django 4.2.11 on 2025-12-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0007_alter_sitevisitreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitreport',
            name='sketch',
        ),
        migrations.AddField(
            model_name='sitevisitreport',
            name='main_sketch',
            field=models.ImageField(blank=True, null=True, upload_to='main_sketches/'),
        ),
        migrations.CreateModel(
            name='ReportSketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='note_sketches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='coreapi.sitevisitreport')),
            ],
        ),
    ]
