# Generated by Django 4.2.11 on 2026-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0008_remove_sitevisitreport_sketch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitreport',
            name='target_folder',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
