# Generated by Django 4.2.11 on 2026-01-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0011_folderchatvisit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folderchatvisit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='folderchatvisit',
            name='user',
        ),
        migrations.DeleteModel(
            name='FolderChatMessage',
        ),
        migrations.DeleteModel(
            name='FolderChatVisit',
        ),
    ]
