# Generated by Django 4.2.11 on 2026-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0012_alter_folderchatvisit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitreport',
            name='completion_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitevisitreport',
            name='generated_pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
