# Generated by Django 4.2.11 on 2026-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0013_sitevisitreport_completion_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitreport',
            name='office_file_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
