# Generated by Django 4.2.11 on 2026-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0014_alter_sitevisitreport_office_file_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('unique_file_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('bank_code', models.CharField(max_length=10)),
                ('district_code', models.CharField(max_length=10)),
                ('sequence_no', models.IntegerField()),
                ('applicant_name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=100)),
                ('bank_ref_no', models.CharField(max_length=100)),
                ('site_staff_code', models.CharField(max_length=50)),
                ('office_staff_code', models.CharField(max_length=50)),
                ('full_folder_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
