# Generated by Django 4.2.11 on 2026-02-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0015_clientfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_file_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('inspection_date', models.CharField(blank=True, max_length=50, null=True)),
                ('documents_received', models.JSONField(blank=True, default=list, null=True)),
                ('verification_database', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapi.userprofile')),
            ],
        ),
    ]
