# Generated by Django 6.0.2 on 2026-03-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0016_verificationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVettingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_file_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vetting_database', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapi.userprofile')),
            ],
        ),
    ]
