# Generated by Django 4.2.11 on 2026-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0017_documentvettingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationreport',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='person_met_at_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='survey_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentVettingData',
        ),
    ]
