# Generated by Django 6.0.2 on 2026-05-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0018_verificationreport_applicant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftingReport',
            fields=[
                ('office_file_no', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='drafting', max_length=20)),
                ('report_data', models.JSONField(default=dict)),
                ('audit_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafting_verifications', to='coreapi.userprofile')),
                ('report_drafter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafting_current_work', to='coreapi.userprofile')),
                ('site_visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafting_site_visits', to='coreapi.userprofile')),
            ],
        ),
    ]
