# Generated by Django 4.2.11 on 2026-06-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0019_draftingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Leave Record',
                'verbose_name_plural': 'Leave Records',
                'ordering': ['-leave_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('source', models.CharField(choices=[('file_completion', 'File Completion'), ('report_signed', 'Report Signed'), ('bonus', 'Bonus'), ('admin_adjustment', 'Admin Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('earned_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Credit Entry',
                'verbose_name_plural': 'Credit Ledger',
                'ordering': ['-earned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('files_done', models.IntegerField(default=0)),
                ('files_target', models.IntegerField(default=125)),
                ('hours_worked', models.FloatField(default=0)),
                ('hours_target', models.FloatField(default=200)),
                ('overtime_hours', models.FloatField(default=0)),
                ('pd_cases', models.IntegerField(default=0)),
                ('npa_cases', models.IntegerField(default=0)),
                ('project_cases', models.IntegerField(default=0)),
                ('other_cases', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performance', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Monthly Performance',
                'verbose_name_plural': 'Monthly Performance Records',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
