# Generated by Django 6.0.2 on 2026-06-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0021_worksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_per_day', models.IntegerField(default=5)),
                ('credits_per_file', models.IntegerField(default=6)),
                ('hours_target', models.FloatField(default=176.0)),
                ('max_session_hours', models.FloatField(default=10.0, help_text='Auto-logout after X hours of work in a single day.')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
