# Generated by Django 6.0.2 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0022_systemconfiguration_overtimerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
