# Generated by Django 6.0.2 on 2026-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0023_systemholiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfiguration',
            old_name='credits_per_file',
            new_name='credits_other',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='credits_npa',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='credits_pd',
            field=models.IntegerField(default=2),
        ),
    ]
