# Generated by Django 6.0.2 on 2026-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0024_rename_credits_per_file_systemconfiguration_credits_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
