# Generated by Django 6.0.2 on 2026-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0025_leaverecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift_timing',
            field=models.CharField(blank=True, default='09:00 AM - 05:30 PM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('absent', 'Absent'), ('wfh', 'Work From Home'), ('late', 'Late Coming'), ('half_day', 'Half Day')], max_length=10),
        ),
    ]
