# Generated by Django 4.2.11 on 2026-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0026_userprofile_profile_picture_userprofile_shift_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='duration',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cl_balance',
            field=models.FloatField(default=1.0, help_text='Casual Leave balance (resets monthly, 1/month)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='el_balance',
            field=models.FloatField(default=0.0, help_text='Earned Leave balance (carries forward, ~15/year)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='late_count_this_month',
            field=models.IntegerField(default=0, help_text='Number of late arrivals this month (resets on 1st)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sl_balance',
            field=models.FloatField(default=1.0, help_text='Sick Leave balance (resets monthly, 1/month)'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('absent', 'Absent'), ('wfh', 'Work From Home'), ('late', 'Late Coming')], max_length=10),
        ),
    ]
