# Generated by Django 4.2.11 on 2026-06-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0027_leaverecord_duration_userprofile_cl_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='User ID assigned in the eSSL/ZKTeco physical device', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BiometricPunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(help_text="The raw ID from the machine, e.g., '100'", max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('punch_type', models.CharField(max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_punches', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Biometric Punch Log',
                'verbose_name_plural': 'Biometric Punch Logs',
                'ordering': ['-timestamp'],
                'unique_together': {('device_user_id', 'timestamp')},
            },
        ),
    ]
