# Generated by Django 6.0.2 on 2026-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0028_userprofile_biometric_id_biometricpunchlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biometric_id',
        ),
        migrations.AddField(
            model_name='worksession',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksession',
            name='total_break_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BiometricPunchLog',
        ),
    ]
