# Generated by Django 6.0.2 on 2026-06-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0029_remove_userprofile_biometric_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='source',
            field=models.CharField(choices=[('report_signed', 'Report Signed'), ('bonus', 'Bonus'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('Report', 'Report'), ('Other', 'Other Documents')], max_length=20)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('PD', 'PD (2 Credits)'), ('OTR', 'OTR (6 Credits)')], max_length=10, null=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='coreapi.userprofile')),
            ],
            options={
                'verbose_name': 'Document Signature',
                'verbose_name_plural': 'Document Signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
    ]
